### ISSUE TITLE
Error on macOS

### ISSUE THREAD

**Issue by 101Dude** [noobj2/Anki_Change_Interface_Font#10]
This is the only extension I have installed on a new and first install of Anki. 

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.1.1-x86_64-i386-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-13 13:36:37
Add-ons possibly involved: ⁨Change Interface Font⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/john/Library/Application Support/Anki2/addons21/1431333984/Change_Font.py", line 163, in open_window
    font_dialog = FontDialog()
  File "/Users/john/Library/Application Support/Anki2/addons21/1431333984/Change_Font.py", line 26, in __init__
    self.mainWindow()
  File "/Users/john/Library/Application Support/Anki2/addons21/1431333984/Change_Font.py", line 30, in mainWindow
    self.setWindowFlags(Qt.Dialog | Qt.MSWindowsFixedSizeDialogHint)
AttributeError: type object 'Qt' has no attribute 'Dialog'

Python 3.11.5

**Comment by noobj2** [comment]
Hey
I'm sorry my life was really busy when you opened the issue. Missed the notification, I guess.

The add-on works on the latest version of Anki.
Do you still have any issue with the add-on?
